### ISSUE TITLE
Compile All button

### ISSUE THREAD

**Issue by Reverbe** [marklagendijk/WinLess#100]
I'm currently using a file structure / LESS structure that requires me to compile multiple files placed on different folders (theme files that pull the base less files).

I'm wondering if it's possible to put a 'compile all' button that would become active the moment you're having multiple folders selected in the left pane (the folders pane).

Right now I have to click compile for each folder individually.

Oh and tanks a lot for this awesome piece of software. My life would be hard without it. :)

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
