### ISSUE TITLE
Open letter: future of WinLess

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/WinLess#104]
Dear users :),
The first version of WinLess was released in October 2011. Back then LESS was just beginning to catch on, and there weren't a lot of tools which supported it. A colleague of mine, an OSx user, showed me [LESS.app](http://incident57.com/less/), a tool with which you could easily have your LESS files watched, and automatically compiled.
I thought that there should be a similar tool for Windows. There wasn't. It seemed to me that making such a tool should be quite simple, 'how hard can it be?', right? I had already found a script with which you could compile LESS files via the Windows command line (back then node.js didn't run on Windows, or you had to compile it yourself or something).

That was how WinLess was born. Creating WinLess turned out te be actually as simple as it seemed (just a bit of GUI on top of a command line script), and it didn't take that much time.

Since then, much has changed. LESS has become more widely adopted. Proper IDE's such as WebStorm (and other JetBrains IDEs, and probably other IDEs, too) have build-in support for LESS compiling. Apart from that there are now lots of [WinLess-kind-of-tools](https://github.com/less/less.js/wiki/GUI-compilers-that-use-LESS.js) available. Fun fact, the sentence 'try out the different LESS tools available for your platform, to see which one fits you best.' on that Wiki page was written by me. I never believed that WinLess was necessarily the best / only good tool out there. It just happened to be the first one for Windows (SimpLESS came out a month later).

Because I currently use WebStorm and PHPStorm for all my programming work, I don't really use WinLESS myself anymore.
Currently WinLESS has 38 open issues. These issues consist of several bugs and lots of requests for certain new features.
I could say this is because I don't have enough free time. However, I think that would be a bad excuse. I think the real reason is that it just doesn't have a high enough priority for me. I do have some time, which I can spend on open source projects, but I am using that time for Angular related projects.

I don't think my amount of free time, and / or priorities are likely to change very soon. I am wondering what should happen with WinLess. If the other tools have all the good aspects of WinLess + more, then WinLess should just die, and everybody should use such other tool.
On the other hand WinLess has 2500+ downloads / month, and around 40.000 downloads total. So there are quite some people currenly using it.
What do you guys think?

If there still is a good reason to keep WinLess around, it would be best to find somebody else to maintain it. I just can't give it the time which it (might) deserve.
Are you that someone?

Yours faithfully,

Mark Lagendijk

**Comment by cnanney** [comment]
Despite its warts, I still use WinLess daily because it's simple, and it works. I've tried SimpLESS and it craps out and gives errors on the exact same files that WinLess compiles just fine, and I found setting up file watchers inside Jetbrains a bit too cumbersome.

Most issues on the tracker have to do with keeping LESS up to date, and properly watching folders for changes. Once those are ironed out, I don't see WinLess as a real time-suck of development. It is only meant to do one thing, and once it does that bug-free, you don't really need to worry about constantly adding features to it.

In my eyes, WinLess needs only two things to be perfect:
1. Ability to add just a single file, and not a whole folder. Most frameworks have a shit-ton of includes, but all you really care about is watching the main file, i.e. bootstrap.less, for changes up along its include paths. Kinda silly to add the folder and have to deselect all other files except the one you care about compiling.
2. On every compile, refresh the list of files you watch for change. If I add some include files and manually compile, those newly added files aren't watched for changes unless I restart WinLess. Issue #73.

To me, that's all you need and it would be perfect. I also think you should make it easier to accept donations for WinLess. Obviously there is a demand for it, and if only 1% of your monthly downloads chipped in $5, that's $125 you didn't have before. Maybe that makes the idea of spending an hour or two of development time per month in upkeep not so bad. I purchased your CalendarMark thing a long time ago even though I had no use for it, just to try and support you.

Despite there being other LESS compilers out there for Windows, I still find yours the best, and I'm sure a lot of others do too. Whatever you decide, thanks for giving us WinLess.

**Comment by sprynm** [comment]
Since this posting, I have tried the few remaining options for PC that don't require an IDE and none so far have matched the features and functions of Winless.  LESS is maturing nicely and rivaling SASS with its new features so I would be keen to see this program maintained.  For instance, source maps would be a fantastic resource for my team.

I too will continue to use Winless daily and wish very much that I had the programming chops to contribute to its long term survival.  If there is some other way, please let me know.

**Comment by maxx0r** [comment]
Goedemiddag Mark ;)

I use winless quite a lot, because I like it better than the IDE compilers. It works quite good for me. Only thing I would like, is an option to create sourcemaps. Apart from that it does what it says on the tin, which is all I need.

**Comment by Andbax** [comment]
It's just the best .less compiler around.
Please keep up your great work.

**Comment by smajl** [comment]
Spent some great times with WinLess, thank you for that Mark, but unfortunately it got somewhat outdated and felt unmaintained and problems emerged. Switched to Koala like month ago (source-map support added this week) and I am now satisfied. 

WinLess definitely needs a few bugfix touches here and there and since your priorities changed (I totally get that - loving Angular too :D) it maybe needs to be passed to another maintainer or so. :)

I wish you all the best and thanks again for this useful tool. :)

**Comment by marklagendijk** [comment]
I decided to write a new version of WinLess using node-webkit. See issue #116.
