### ISSUE TITLE
Parenthis not required for operations?

### ISSUE THREAD

**Issue by jeromeip** [marklagendijk/WinLess#106]
_Disclaimer: Forgive me as this is a "newbie" report so maybe not an actual issue!_

I read that mathematic operations now need parenthesis (since less 1.4.0).
However, my declaration without parenthesis:

```
border-radius: 12em / 3em;
```

was interpreted unexpectedly as an operation and became:

```
border-radius: 4em;
```

So I had to escape it this way: 

```
border-radius: ~"12em / 3em";
```

to get the proper result. 

Is this normal?!

**Comment by marklagendijk** [comment]
@jeromeip yes, this is normal, because it `strict math` has to be explicitly enabled:
`--strict-math=on|off     requires brackets. This option may default to on and be removed in the future.`

WinLess currently has no way to allow you to set such options.
Questions are always welcome. If you would want support for this feature, please open a feature request for it.
