### ISSUE TITLE
"Close to Tray" option

### ISSUE THREAD

**Issue by davestewart** [marklagendijk/WinLess#108]
I frequently hit the close button and WinLESS exits.

Would be great to have a "Close to Tray" option, as I'm always having to restart the app :(

If I want to quit, a File > Quit menu item would do the job.

**Comment by ghost** [comment]
+1. If your app "sits" in the tray area it would be good to have an option to minimize instead of closing. Always minimizing instead of closing wouldn't hurt too as the tray icon already has the Exit option.

**Comment by ghost** [comment]
+1

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
