### ISSUE TITLE
Add "monitor" and "group" options to monitor individual file changes and compile output

### ISSUE THREAD

**Issue by ruslanurban** [marklagendijk/WinLess#114]
The "monitor" option (checkbox) would allow monitoring individual file updates. The "compile" option would indicate which files to need to be compiled when any of the files that are being monitored get updated.
The "group" option (textbox) would allow specifying which files need to be compiled upon a change in a monitored file. The monitored group can be initialized with the name of the directory.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
