### ISSUE TITLE
Does not report error with Minify on

### ISSUE THREAD

**Issue by K-Thompson** [marklagendijk/WinLess#118]
WinLess v. 1.8.3. LESS.js v. 1.7.0

From Bootstrap v3.1.1 source, compile alerts.less with Minify selected. 

WinLess reports a successful compile. This is wrong. No css file is created.

Turn "Minify" feature off. Now compile. WinLess correctly reports an error:

@alert-padding is undefined.

EDIT: This is not the same bug as #115. The source should not compile. The issue is the error is not reported when Minify is on.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
