### ISSUE TITLE
Keeps compiling file forever

### ISSUE THREAD

**Issue by nasl** [marklagendijk/WinLess#121]
Mapped remote SFTP folder to a drive through "SFTPdrive" and WinLess keeps compiling the same file over and over even if it is closed and not touched anymore
![capture](https://cloud.githubusercontent.com/assets/7279859/2689381/91f42e16-c300-11e3-9d42-17d1e64ec4e6.PNG)

**Comment by nasl** [comment]
hmm, seems work ok with "ExpanDrive" for now.

**Comment by nasl** [comment]
nope, seems the problem is the same

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
