### ISSUE TITLE
fatal error when compile less filles

### ISSUE THREAD

**Issue by DessiG** [marklagendijk/WinLess#128]
Hi,
I have a solution in Visual studio 2012 and we compile our less files in Winless, but I get an error for one of the less files - FATAL ERROR:js allocation failed - process out of memory
How can I understand from where comes this error.
Thanks,
Desi

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
