### ISSUE TITLE
Recursive watch of @import files for auto-compile

### ISSUE THREAD

**Issue by aMUSiC** [marklagendijk/WinLess#129]
Consider this scenario:

I have master.less which imports a.less
then a.less imports a1.less, a2.less and a3.less

WinLess is set to auto-compile upon changes and the only file I monitor is master.less (outputing to master.css)

If I change anything on "a.less", then WinLess will successfully understand that there has been a change since a.less is part of master.less's imports

However if I change anything on a1.less, a2.less or a3.less, then auto-compilation is not triggered.

I suggest a feature where WinLess will recursively build a map of the @import tree so it automatically compiles on any project's file change.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
