### ISSUE TITLE
Could it make the same with js files?

### ISSUE THREAD

**Issue by marquex** [marklagendijk/WinLess#13]
Hi Mark!

I've just discovered your winless, and I think it will be mandatory for all my projects now on!! Thank you so much for you work!

I could't find other way to contact  you, so I write this idea here.

Once I used it I change my less files to import every css file inside, this way I got one file with all the css compressed. That was great, and quickly I needed the same for all the js files, but there's nothing similar on the web.

You already have the program made and I think It won't be so hard to include a js combinator and compressor that everytime a js file is modified automatically compiles to a single minified file.

Maybe it is out of the scope of winless, but wouldn't be great? If you decided to implement it you will be famous otherwise thanks again for winless, it's a jewel :)

javi@marquex.es

**Comment by marklagendijk** [comment]
> Maybe it is out of the scope of winless, but wouldn't be great?

Yes, and yes. I do think it would be very nice if there would be a program which works as simple as WinLess which could also minify javascript.
There are two reasons why I won't be making this program:
1. It would be a new project. Adding such functionality to WinLess wouldn't make sense (although WinLess could be used as a base for the new project).
2. It would be a big project. When you think about what the program should ultimately do, you end up with the GUI equivalent of [wro4jRunner](http://code.google.com/p/wro4j/wiki/wro4jRunner). Not only would it be quite some work to implement the program properly, but keeping all the processors up to date would also be a challenge.

I just don't have the time for a project like this. I already have enough hobby projects. 
For comparison, I made WinLess because LESS.app is Mac only and I thought: 'why doesn't this exists on Windows? This is very easy to make'. It was, the first version of WinLess was made with only a few days work.

**Comment by tomhuze** [comment]
@marquex Here is a web-based tool I am using to do the same thing I think you want to do: http://refresh-sf.com/yui/
I learned about it from this question on Stack Overflow, which suggests other options (including native apps) as well: http://stackoverflow.com/questions/23745/does-a-yui-compressor-gui-app-exist
