### ISSUE TITLE
no checkboxes on high PPI displays

### ISSUE THREAD

**Issue by waldo22** [marklagendijk/WinLess#134]
I am unable to use WinLess on my 4k monitor due to the checkboxes not displaying properly.
![no_checkboxes](https://cloud.githubusercontent.com/assets/3190286/4477752/31c64a5e-4980-11e4-86b6-2c9b47e291e6.png)

I have had this issue on other programs (such as Quickbooks), but in WinLess I am unable to adjust the column width of either the compile column or the minify column, so I can not make the checkboxes visible.

A short term solution would be to make these column widths adjustable.

What do you think?

-Wes

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
