### ISSUE TITLE
Compiler Error: Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by fseminario** [marklagendijk/WinLess#135]
Not sure when this started happening but in older versions this errors was fixed by just saving the file twice. 

Basically I am updating an include file  that forces the bootstrap.less file to compile. I can get around this error by manually forcing the compile.

![screen shot 2014-10-02 at 2 21 42 pm](https://cloud.githubusercontent.com/assets/4037582/4496005/33748c62-4a61-11e4-8cda-1e19eabf7a1e.png)

Files are worked over FTP or Network so there is a slight delay until the file is transferred. Perhaps a delay might help since that would allow the file to be transferred successfully. Codekit has a delay feature which helps out tremendously when working over network or FTP.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
