### ISSUE TITLE
Option to Split CSS File Output for IE Selector Limitations

### ISSUE THREAD

**Issue by matthew-valenti** [marklagendijk/WinLess#140]
Consider an option to split final css into multiple files for compatibility with IE6-9 selector limitations.
i.e.
A sheet may contain up to 4095 rules
A sheet may @import up to 31 sheets
@import nesting supports up to 4 levels deep

http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
