### ISSUE TITLE
Write Compile Errors to a Log File

### ISSUE THREAD

**Issue by mtwalsh** [marklagendijk/WinLess#15]
Firstly, many thanks for producing and sharing this app, it's come in really handy.

We're using the app on a central development server, so the system tray notifications are not seen as we each have our own workstations.  Would it be possible to write the compile errors to a log file that we can store in a particular folder that all team members can access?

Thanks.

**Comment by marklagendijk** [comment]
Having to check a logfile to see whether your latest change to a LESS file didn't break anything doesn't sound very practical. But neither does a 'central development server'. What happens if two people change the same file? And if person a breaks something, person b won't be able to continue with his work.
I won't go into this any further, but generally not having individual development environments and version control is a bad idea.

Anyway, you are saying that people can change files on the server, but cannot see the system tray notifications. Ergo they  access the filesystem and aren't using remote desktop.
What you could do is just have each developer which needs to change the LESS install WinLess. They then each add the .less files on the development server to their local instance of WinLess. Problem solved.

**Comment by marklagendijk** [comment]
WinLess is a client application and should be used as such.
