### ISSUE TITLE
Compiler Result says "success" but doesn't compile

### ISSUE THREAD

**Issue by AntJanus** [marklagendijk/WinLess#16]
I started working on a project this morning and I'm having some trouble with Winless. The compiler states that it compiles, gives me a notification, compiler results states "success" every time I press the compile button but the output file doesn't change.

Just to make sure I wasn't being an idiot, I used crunch and simpless to compile the file and everything worked. I tried to recompile it with winless (it worked yesterday too, i swear) but nothing happened. Again, just to check I wasn't being an idiot, I even opened the file straight from winless (right clicked, open file) rather than through dreamweaver where I work and again, nothing changed. I made sure to switch out a few declarations every time I compiled so I could see if a difference was made but nothing happened. I created random errors in my less files but nothing happened. I even deleted the original output file to see if Winless could generate a new one -> nothing.

Any idea what could be causing this? At some point i ran the app as an administrator, again, just to troubleshoot but nothing happened.

**Comment by AntJanus** [comment]
Another thing I've noticed. When I modify the .less file, it does automatically "compile" but the output doesn't change.

**Comment by marklagendijk** [comment]
The normal behavior would be that if you save changes to a .less file which is watched by WinLess, that it automatically recompiles it.

The 'false positives' is a known problem. There are situations where certain errors aren't correctly returned as errors. In such cases there is no new .css file, but WinLess does report 'success'. I think this problem is caused by a bug in [less.js](http://lesscss.org) itself or else in [less.wsf](https://github.com/duncansmart/less.js-windows).

Try making a very simple less file to see if that works. If it does, the problem is caused by 'some error' in your other LESS code. Use something like:

``` css
.test {
    width: 2+2px;
}
```

Let me know if that does work.

**Comment by AntJanus** [comment]
The simple test works. I created a test.less file and got a test.css file generated with the correct compilation (got compile success as well). So that works.

I'm interlinking a good amount of different files (20 less files maybe?), could that be a part of it? 

Also, sorry for the slow reply.

**Comment by jonketo** [comment]
I have noticed this issue when compiling a file that imports other files. If the other file has an error in it the compiled file will be shown as successfully compiled, but the file is not output. I just compile all my files each time to ensure the errors are not hidden.

**Comment by AntJanus** [comment]
i can't compile them individually because they're inter-dependent (ie. one file has mixins, another color scheme and so on). But I did compile them via several different compilers afterward just to make sure (Crunch, LESS.app, and SimpLESS).

**Comment by jonketo** [comment]
Using multiple compilers is a good idea. I just try to recompile all of them together at once because I am importing mixins as well. I'll take a look at the other apps you mentioned. Thanks.

**Comment by tomhuze** [comment]
I have the same issue with errors in imported files not being reported and generating a false positive compile. It would be really helpful in debugging if WinLess could return an error in these cases, especially in projects with many individual less files being imported into a master less file which provides the dependencies.

**Comment by jonschlinkert** [comment]
Just wanted to add that I have this issue as well with WinLess. However, I have not experienced this issue using less.js with node.js so I'm not convinced it's a less.js issue. It could be less.wsf

**Comment by basher** [comment]
I had a similar problem today, which I then narrowed down to 1 line in a mixin.

I have 1 "mixins.less" file which imports 1 "variables.less" file.
This "mixins.less" then gets imported by all other LESS files.

The line is question was:
background-image: url(@spriteButtonPath);

"mixins.less" said it compiled, as did all the other LESS files, but no new CSS is ouptut.

When I changed the line to...
background-image: url('@{spriteButtonPath}');

...everything worked OK.

This is strange, because I don't embed image path variables in strings like this in any of the other LESS files.
Is this something that's maybe particular to mixins??

**Comment by ndenning** [comment]
I was having the same problem. The culprit: I put two selectors, separated correctly by a comma, on two separate lines. The problem was solved when I put all selectors on one line and allowed the compiler to put them on separate lines. So this caused problems:

.selector1 > .child,
.selector2 {
property: value;
}

But this fixed the problem:

.selector1 > .child, .selector2 {
property: value;
}

Edit: I found that this was specific to also using child selectors in conjunction with putting the selectors on separate lines, so I changed the example above to reflect that.

**Comment by AntJanus** [comment]
@ndenning  interesting. I wish dreamweaver supported LESS fully, then I could setup code formatting to batch all of my files. :/

**Comment by meisterkaiser** [comment]
two specific cases where this also occurs:

accidentally using "=" instead of ":" in a variable definition (e.g. @var = 20px; )

or

having an accidental semicolon at the end of a line (e.g. @var:20px;; )

at least there should be no success msg ...

**Comment by marklagendijk** [comment]
WinLess updated to compiling via lessc with Node.js. 
This should fix most compiling bugs. 
Compiling bugs that still exist should be reported at the [less.js project](https://github.com/cloudhead/less.js).

**Comment by ghost** [comment]
I couldn´t compile with multiples @imports either.
I tried Crunch app (http://crunchapp.net/) and it got the job done!!
