### ISSUE TITLE
Folder rename causes runtime error

### ISSUE THREAD

**Issue by allardvanhelbergen** [marklagendijk/WinLess#24]
Running: Win7, WinLess 1.5.3, Less.js 1.3.0

Steps to reproduce:
- Click Add folder > select folder > Click OK
- In windows explorer, rename the folder 
- Back in WinLess, with folder selected, click Refresh folder
- Unhandled exception occurs

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
