### ISSUE TITLE
Incorrect backward file path when using @import in nested folder

### ISSUE THREAD

**Issue by paustria** [marklagendijk/WinLess#52]
Here is the scenario.
I have _mixins.less_ in less folder (~\less\mixins.less) with the following code.

`background: url(../images/Zurb/bg-feed-top.png) repeat-x scroll 0 0 #FFFFFF;`

let's say I have _site.less_ in less\app\facebook folder (~\less\app\facebook\site.less)
I import _mixins.less_

`@import "../../mixins";`

In this case, the compiled code in _site.css_ should be

`background: url(../../../images/Zurb/bg-feed-top.png) repeat-x scroll 0 0 #FFFFFF;`

However, the compiled code in _site.css_ is
`background: url(../images/Zurb/bg-feed-top.png) repeat-x scroll 0 0 #FFFFFF;`

**Comment by marklagendijk** [comment]
This is the default behaviour of LESS: relative paths aren't rewritten but remain exactly as they are in the source file. LESS does offer rewriting by specifying some option, though. I might look into building that option into WinLess.

**Comment by ReneDrie** [comment]
I've got the same issue. Also with a forward path.
Working on OSX with Less.app it does work. But changing the files in a Windows environment with WinLess breaks all the url attributes the same as paustria.
Would be great if this can be fixed, since we use Less the make the code nicer and we don't want 20+ less files in 1 folder.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
