### ISSUE TITLE
Feature: Output error report/message to .css

### ISSUE THREAD

**Issue by camedia** [marklagendijk/WinLess#56]
Due to limitations in our development environment (multiple team members, permissions and server config) it's not possible for several team members to see the WinLess UI and console for feedback in identifying errors.

Can you provide an option to output the error report/message directly to the .css file as plain text for viewing through the browser? Either way, thanks for the fantastic program!

Cheers,
/chris

**Comment by leggomuhgreggo** [comment]
Would like to add my support for this enhancement--would be killer. Thanks!

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
