### ISSUE TITLE
Ability to convert 1 less file to multiple css files

### ISSUE THREAD

**Issue by ghost** [marklagendijk/WinLess#58]
I would like the ability to convert a less file to a minified and a non-minified version.

The way I do this now is have 2 files:
style.less => style.css (non-minified)
style.min.less => style.min.css (minified)
And in the style.min.less I just have:
`@import "style.less";`
This works, but requires all these extra .min.less files.

So would be cool to have this be done automagically by WinLess.

**Comment by ruslanurban** [comment]
+1

**Comment by ghost** [comment]
bump...

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
