### ISSUE TITLE
CLI opens another instance

### ISSUE THREAD

**Issue by dieulot** [marklagendijk/WinLess#6]
Hi, when I use WinLess via CLI and already have another instance of WinLess running I get two WinLess in the system tray, and if I close the old one first my previous directories that were being watched are lost, it just happened to me right now.

What would be usable is if invoking WinLess via CLI would add the directory to the list we already have, without opening a second WinLess. I must add the directory via the GUI otherwise.

**Comment by marklagendijk** [comment]
I think your use case is quite unique. You want to use both methods at the same time.

WinLess' design is simple: it remembers the last opened files. If you open multiple instances it will remember the files from the instance which is closed last.

Your suggestion would indeed work nicely. I think it would be hard to implement, though. There would have to be a) a check to see if WinLess is already open, and b) a way to communicate to the already open instance.

Because of this I'm afraid I won't support your use case. You can either:
-Put a call to winless.exe with all the paths in a command line script.
-Add new paths via the GUI.

I would recommend against opening multiple instances of WinLess.
