### ISSUE TITLE
WinLess (update) information

### ISSUE THREAD

**Issue by nomadpgmr** [marklagendijk/WinLess#62]
It would be nice to know when a new version is available and where to go to get it.
1. Add link in help menu to http://winless.org/

Add one or more of following
2. Show Current Released version and Current Installed Version in about screen. Could include a link to new version in help screen.
3 Somehow display if a new version is available. This can be via a Display of the current released and current installed version on startup or a small status line below the files dialog, a popup on start-up, or on the help menu. 
5. Add link in help menu to latest download (github).

Thanks!

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
