### ISSUE TITLE
WinLess autocompile fails with network files

### ISSUE THREAD

**Issue by lltallada** [marklagendijk/WinLess#64]
Hi,
I'm using WinLess in a bootstrap + twig project on a Win7 machine.
The .less files are in a Linux machine so i'm using samba mounted network drive to access them.

Everytime i start WinLess and make the first change to any .less file the compiler works as expected, automatically compiling .less files. But after that first automatic compile, I have to compile the .less files manually to see the changes in the browser because it seems that WinLess is not able to detect the changes on my .less files.

I've tested WinLess on local files with any issues.

Thanks for your time.
Lluís.

**Comment by marklagendijk** [comment]
That sounds like an annoying issue. However, I'm afraid there isn't much I can do about it.
WinLess just uses the default system component for watching folders for changes to any files. When this component doesn't detect a change, there isn't much WinLess can do.

**Comment by kitsguru** [comment]
I also use a linux server with Samba and had no difficulty with winless compiling network files, until a few days ago. 

I realized that the clocks were out of sync. My Win7 machine had failed to sync for several weeks and was running almost a minute behind. I did a manual time sync and now winless auto-compiles again.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
