### ISSUE TITLE
WinLess forgetting my folders/files?

### ISSUE THREAD

**Issue by thekeogh** [marklagendijk/WinLess#65]
I have a VirtualBox running Ubuntu server that I use for all my sites, and I drag my folders to the WinLess folder pane and all is well and it works a treat.

I have my VB running as a service, and in most cases on reboot of my Windows machine its all fine, but if on boot of my Windows machine my VB doesn't load in time, WinLess doesn't see the path to my folders so removes them from the list.

So basically, if I add "/ubuntu/path/to/less" to my folder listing on WinLess, if WinLess no longer sees "/ubuntu/path/to/less" it will remove it from the list. Then I have to add it back which is quite annoying, especially if I have a few.

Can we have a feature where it will ALWAYS remember the folder listing on the left, if it can't find the folder simply ignore it until it does but never remove it from the list?

Hope that makes sense!

**Comment by marklagendijk** [comment]
Your issue does make sense. WinLess has an automatic cleanup feature, which is giving your problems.
I will list this as a feature request for an option to disable this automatic cleanup feature.

**Comment by thekeogh** [comment]
Perfect, thanks Mark!

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
