### ISSUE TITLE
WinLess not watching newly added files for changes

### ISSUE THREAD

**Issue by cnanney** [marklagendijk/WinLess#73]
When I add new LESS files to a project, then `Refresh Folder` from within WinLess, it will show the new files, but not monitor them for changes. You must restart the app for it to watch the new files.

I think when you refresh the folder, it should restart whatever file-monitoring process you use to pick up the new files.

**Comment by smajl** [comment]
+1 This happens to me too.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
