### ISSUE TITLE
WinLess won't let me chose install dir

### ISSUE THREAD

**Issue by ozh** [marklagendijk/WinLess#77]
I think that's a major defect, especially when dealing with computers with very strict security policy where "Program Files" is not writable if you don't have admin privs

**Comment by marklagendijk** [comment]
Personally, as a developer, I would never accept to work on a pc without admin rights ;).
Is this specific issue a problem in your sitiuation?

I'm closing this issue since this I'm not going to fix this. I currently use 'WarSetup' which is a very simple (but also basic) tool for creating installers.
However, pull requests are always welcome.
