### ISSUE TITLE
command line compile a single file (-f), or files

### ISSUE THREAD

**Issue by rhermann** [marklagendijk/WinLess#79]
Directory watching is ok, but what about a "-f" for giving directly files to compile. Because I have a lot of less files, importing other, wich are combined in a single file.

**Comment by mroswald** [comment]
+1

**Comment by rhermann** [comment]
If the WinLess author will accept this pull https://github.com/marklagendijk/WinLess/pull/99 then the feature could be official. I compile it now for my own, until it this go public.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
