### ISSUE TITLE
Winless Update Not Working

### ISSUE THREAD

**Issue by takuhii** [marklagendijk/WinLess#85]
Winless is suggesting that an update to less.js v1.4.2 when i hit update it updates me to v1.3.3 and refuses to actually update to 1.4.2. I also can't see how to do it manually :/

**Comment by smajl** [comment]
Please, search the recent issues next time, this have some many duplicates.
E.g.: https://github.com/marklagendijk/WinLess/issues/82, https://github.com/marklagendijk/WinLess/issues/69 and so on.

Solution: run WinLess as administrator or perform manual NPM update.

**Comment by ghost** [comment]
So the solution to a bug in WinLess is not to fix it but to have the user manually update it (I have no idea how to do a manual NPM update).

**Comment by marklagendijk** [comment]
@nonumber that is not the solution, but a workaround. I haven't had time yet to find and implement a solution. If you do have the time and would fix this, I would surely merge the pull request ;).

Anyway, I released an update of WinLess with the new less.js to temporarily fix this.
This issue is an dupplicate of #82.

**Comment by ghost** [comment]
Thanks.

Sorry about tone in previous post. Caught me on a bad day.

**Comment by ghost** [comment]
I updated to the new version and now the whole list of files is gone from WinLess... :(

**Comment by takuhii** [comment]
I have NO IDEA what an NPM update is?

**Comment by ghost** [comment]
See: https://github.com/marklagendijk/WinLess/issues/69#issuecomment-18610214
