### ISSUE TITLE
Inaccurate info on download button

### ISSUE THREAD

**Issue by wbraynen** [marklagendijk/WinLess#87]
Thanks for the soft!  One easy fix: here's a screenshot of some inaccurate info that surprisingly caused some problems during download over a slow connection.  (I would either correct the mb promise or remove it.)

![screenshot](https://f.cloud.github.com/assets/4765449/915220/09192b90-fe62-11e2-9451-cf4a48e60406.png)

**Comment by leskowski** [comment]
I spotted this too.  Is the correct size 7mb or should it be 3?

**Comment by marklagendijk** [comment]
The size on the image is just incorrect. I should correct it some day (or remove the size altogether).

**Comment by leskowski** [comment]
I guess there are more important things..but thanks for confirming.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.

**Comment by wbraynen** [comment]
Form a usability point of view, I think this is actually a bug.  (I think it's OK to remove the size.)
