### ISSUE TITLE
WinLess Doesn't Watch Files on Different Drive

### ISSUE THREAD

**Issue by jtwebb** [marklagendijk/WinLess#88]
I have my "main" drive `C:\` and a storage drive where I keep all my projects `E:\`

If I move the folders to `C:\` then WinLess will watch the files and compile them on save. However, when I have my folders on my `E:\` drive WinLess won't watch them, I have to manually compile them. Is this a known bug or is there a resolution for this problem?

**Comment by APlusDesign** [comment]
I also have this issue, using a partition for virtual hosts D:\ while winless is installed on C:\ and it will not watch files.

**Comment by jtwebb** [comment]
I switched to using http://koala-app.com/. It works even when your files are on a separate drive.

**Comment by APlusDesign** [comment]
Thank you jt, koala works quite well. The office will be switching to it on Monday. Sorry winless, it was good while it lasted.

**Comment by smajl** [comment]
Trying Koala. Seems working well. ;)

Maybe when WinLess gets back to working state I will gladly come back - it has been a long relationship. ;)

**Comment by ghost** [comment]
Here is the same problem ... WinLess not watching the files ... It compile only if I click the Compile button. I liked it but with this issue it is not handy any more ...

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
