### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by shawng** [marklagendijk/WinLess#95]
Now that WinLess supports LESS 1.5, it would be great to have an option to generate .map files for source maps.

**Comment by luiz-bonfa** [comment]
I second that!  There are four new flags related to source map generation that lessc 1.5 accepts.
This feature of WinLess will be greatly appreciated.

**Comment by bazjapan** [comment]
+1

**Comment by sprynm** [comment]
+1

**Comment by lutano** [comment]
+1

**Comment by jpblancoder** [comment]
+1

**Comment by prantor19** [comment]
+1

**Comment by xhoskin** [comment]
+1

**Comment by webteamprosteps** [comment]
+1

**Comment by kennytheecat** [comment]
+1

**Comment by Reverbe** [comment]
+1

**Comment by arafays** [comment]
+1

**Comment by jeepstone** [comment]
Thank you for your email.

I am out of the office until Monday 7th July. Please contact Steve Tustin on 01242 573311 for any urgent enquiries.

Kind regards,
Pete

**Comment by chandon** [comment]
To do that, just open WinLess\node_modules\.bin\lessc.cmd and add : 
--source-map
at the end of the line 2 and 4 of the file

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.

**Comment by ahoyahoy** [comment]
@chandon thank you!
