### ISSUE TITLE
Exclude files prefixed with an underscore _

### ISSUE THREAD

**Issue by shawng** [marklagendijk/WinLess#96]
There is a convention to have "partial" .less files prefixed with an underscore to indicate that it isn't a standalone file but is meant to be imported into other files.  These partial .less files often don't compile on their own because they don't import the variables and mixins they reference.  For example "bootstrap.less" would compile but "_alerts.less" wouldn't compile.

It would be great to exclude .less files that start with an underscore from being compiled.  This would avoid a long list of error messages when compiling large .less projects.

**Comment by ruslanurban** [comment]
+1

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
