### ISSUE TITLE
Need to add folders every time I restart Windows

### ISSUE THREAD

**Issue by hchouhan** [marklagendijk/WinLess#97]
Hi,

Every single time I restart my Windows, I have to add folders to WinLess for compiling. I have restarted it as Admin, etc. but it keeps happening again.

**Comment by ukozdan** [comment]
I have some large Less projects involving a lot of folders and different outputs, so to lose these setups upon updating is a big deal. It would be great if this information could be preserved, or to decide whether to keep the old settings, or do a fresh install.

**Comment by marklagendijk** [comment]
Closing all issues.
WinLess 1.x is now in maintenance mode. This means that at this time no feature requests will be accepted. Bug reports are still welcome, but all current issues are closed to make sure that the open issues are only about current bugs.

WinLess 2.x is a rewrite of WinLess using node-webkit. The development of [WinLess 2.0](https://github.com/marklagendijk/WinLess/tree/winless2) can be followed [here](https://github.com/marklagendijk/WinLess/issues/116). Most of the work is done, however, since my priorities have shifted it is now not clear whether it will ever be finished. Feature requests will only be accepted after the 2.0 release.
